### ISSUE TITLE
Jellyfin 10.8 Plugin NotSupported

### ISSUE THREAD

**Issue by ilkersigirci** [ankenyr/jellyfin-youtube-metadata-plugin#51]
Earlier today, Jellyfin 10.8 officially out but the plugin status show as "NotSupported"

Tried both linuxserver and jellyfin docker images. Same result.

Platform: linux
method: docker installation

**Comment by labor4** [comment]
...also ```apt``` repo install on Ubuntu Focal

**Comment by ankenyr** [comment]
I just released a new version that should support 10.8 and added it to the manifest so you should be able to install it via the plugin repo.
I don't know what `apt` has to do with this since you do not get plugins via that. Going to mark this as closed.

**Comment by labor4** [comment]
"apt":
of course not 😊.
i tried to imply that any possible setup/layout difference deriving from a container are out of scope. not that i am really knowledged about it. 

thanks a lot!
gonna test right away!
regards

**Comment by labor4** [comment]
@ankenyr 
Note:
Installed, as in
```
root@jellyfin:~# find /var -name YoutubeMetadata*
/var/lib/jellyfin/plugins/YoutubeMetadata_1.0.3.7
```
but the version still displays `1.0.3.6`:
<img width="309" alt="string" src="https://user-images.githubusercontent.com/18475375/173204857-d399128a-669b-45a4-99bb-816b78cc537e.png">
It works though.

**Comment by ankenyr** [comment]
How did you install the plugin originally and how did you update it? I am suspecting you possibly manually copied the files and Jellyfin for some reason did not update the meta.json file in the folder which is its responsibility. You could probably resolve this by removing the plugin via the web UI, deleting the files, and installing via the plugin repo.

**Comment by labor4** [comment]
yes i ran into some problems updating, but took it for a beta leftover, expecting i handled it correctly. 
- at some point in time there happened a manual install yes, but possibly at version .5
- auto update would install your new .7 version, but keep the old version (.6 and .7 visible in the gui). 
- removing .6 via gui worked, i decided to decide both then but gui-remove the remaining .7 would freeze the gui (not even an entry in journalctl -f)
- i applied the find command above and found .5 and .7 (not .6) folders present. 
- i deleted both, and restarted. installed .7 from repo
- thats where i am now. 

i am eager to know if i can force a "cleaner" reset of the plugin (there is no other external plugin installed), because something down the road doesn't make sense to me, not even sure how to formulate an issue: a kind of opposition regarding make-new-previews between "manual image replace via add-missing-metadata" and "periodic media scan". path errors that others report to be solved but that i cannot confirm. the manual image fetcher works mostly (handled by your plugin) while the periodical destroys the images again. in both scans however there are heaps of error entries.

so if there is a better reset needed, i may understand more, "which does what". 

is meta.json the only file i must delete, additionally to the plugin?

**Comment by labor4** [comment]
I just did it again like so:
- Tried GUI-remove the plugin > GUI freeze
- stop jellyfin
- `rm -r /var/lib/jellyfin/plugins/YoutubeMetadata_1.0.3.7`
- I believe `meta.json ` you refered to, is the one in `YoutubeMetadata_1.0.3.7` dir..., so that's handled?
- start jellyfin, install from GUI
- same result (wrong version number)

**Comment by labor4** [comment]
Update:
I tested a completely fresh VM (new Ubuntu 22LTS, with new jellyfin stable).
The GUI says "1.0.3.6", and I cannot uninstall from GUI.
