### ISSUE TITLE
Better support for playlists

### ISSUE THREAD

**Issue by Waldkoenig** [ankenyr/jellyfin-youtube-metadata-plugin#73]
Right now video folders from playlists seem to be treated like channels and thus aren't properly identified.

**Comment by ankenyr** [comment]
Please see [this](https://jellyfin.org/docs/general/server/media/shows/#:~:text=The%20most%20common%20naming%20scheme,best%20results%20when%20scraping%20metadata.) link on how naming and folder structures work in Jellyfin. You need to adhere to their organization. Otherwise you need to explain in a lot more detail what exactly you want.
